[build]
  command = "cd app && npm install && npm run build && cd ../netlify/functions && npm install"
  publish = "app/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["busboy", "@napi-rs/canvas", "pdfjs-dist"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
