[build]
  base = "app"
  command = "npm run build && cd ../netlify/functions && npm install"
  publish = "dist"
  functions = "../netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["busboy"]

[functions."extract-slides"]
  node_bundler = "none"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
