import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type {
  PitchDeckCheckReportV2,
  DashboardEvaluatedContextV2,
  InvestmentCaseV2,
  InvestmentCaseAssessmentV2,
  PriorityImprovementV2,
  SuggestedNextStepV2,
} from '../../lib/types'

// V2 report renderer — dashboard-first layout with a simple three-level
// hierarchy. The left/dashboard side is scannable navigation only; ALL detailed
// reading happens in the right-side detail pane:
//   1. Deck Score      (one selectable summary card, selected by default)
//   2. Deck Feedback   (4 selectable dimension cards)
//   3. Slide Feedback  (one selectable card per slide/topic)
//
// Report substance is generated by canonical report generation.
// This component renders dashboard_feedback directly and must not derive or
// rewrite substantive feedback. When dashboard_feedback is absent (older
// reports), it falls back to the legacy report_v2 fields, rendered directly.

interface V2ReportProps {
  report: PitchDeckCheckReportV2
}

// --- grading -----------------------------------------------------------------

type Grade = 'A' | 'B' | 'C' | 'D' | 'neutral'

const GRADE_UNDERLINE: Record<Grade, string> = {
  A: 'bg-grade-a',
  B: 'bg-grade-b',
  C: 'bg-grade-c',
  D: 'bg-grade-d',
  neutral: 'bg-monarch-border-strong',
}

function cardClass(selected: boolean): string {
  // Selection is signalled by a charcoal (near-black) 2px border + subtle shadow,
  // kept independent of the grade rail so it never reads as a grade color (and
  // never red). `relative overflow-hidden` lets the grade rail clip to the card.
  // Selection is signalled by a faint fill + soft shadow (not a heavy outline);
  // the border stays a plain 1px neutral in both states so the card never
  // competes with the grade rail.
  return `relative border text-left w-full transition focus:outline-none focus-visible:border-monarch-ink ${
    selected
      ? 'border-monarch-border bg-monarch-fill shadow-[0_2px_8px_rgba(0,0,0,0.08)]'
      : 'border-monarch-border bg-monarch-card hover:border-monarch-border-strong shadow-[0_1px_2px_rgba(0,0,0,0.04)]'
  }`
}

const DASH_LABEL: Record<Grade, string> = {
  A: 'Strong',
  B: 'Needs refinement',
  C: 'Under-supported',
  D: 'Missing / weak',
  neutral: 'Not assessed',
}

// A/B/C/D string (from dashboard_feedback grades) -> Grade.
function gradeFromString(s?: string): Grade {
  const c = (s || '').trim().toUpperCase()[0]
  if (c === 'A' || c === 'B' || c === 'C' || c === 'D') return c as Grade
  return 'neutral'
}

// Legacy fallbacks (used only when dashboard_feedback is absent).
function slideAssessmentToGrade(a?: string): Grade {
  switch ((a || '').trim()) {
    case 'Strong':
      return 'A'
    case 'Mostly answered':
      return 'B'
    case 'Partially answered':
    case 'Under-supported':
      return 'C'
    case 'Weakly answered':
    case 'Weak':
    case 'Not answered':
      return 'D'
    default:
      return 'neutral'
  }
}
function deckScoreToGrade(score?: number, label?: string): Grade {
  if (label === 'Strong' || (typeof score === 'number' && score >= 4)) return 'A'
  if (score === 3) return 'B'
  if (score === 2) return 'C'
  if (typeof score === 'number' && score <= 1) return 'D'
  return 'neutral'
}
function overallLetterToGrade(letter?: string): Grade {
  const c = (letter || '').trim().toUpperCase()[0]
  if (c === 'A') return 'A'
  if (c === 'B') return 'B'
  if (c === 'C') return 'C'
  if (c === 'D' || c === 'E' || c === 'F') return 'D'
  return 'neutral'
}

// --- view model ---------------------------------------------------------------
//
// Both the dashboard_feedback path and the legacy fallback produce this same
// normalized shape, so rendering below is source-agnostic.

interface VMContext {
  stage: string
  audience: string
  target_raise: string
  deck_purpose: string
  business_type: string
  confidence: string
  note: string
}
// Investment Case as Presented — qualitative area assessments plus the free-text
// Market Validation evidence line. Rendered verbatim from report_v2.investment_case.
interface VMICArea {
  label: string
  interpretation: string
}
interface VMInvestmentCase {
  investor_fit: VMICArea | null
  market_validation: string
  opportunity_strength: VMICArea | null
  execution_credibility: VMICArea | null
}
interface VMPriorityImprovement {
  title: string
  why_it_matters: string
  what_to_add_or_change: string
}
interface VMNextStep {
  title: string
  detail: string
}
interface VMDeckScore {
  grade: Grade
  title: string
  summary: string
  like: string[]
  question: string[]
  pass: string[]
  focus: string
  investmentCase: VMInvestmentCase | null
  priorityImprovements: VMPriorityImprovement[]
  nextSteps: VMNextStep[]
  context: VMContext | null
}
interface VMFlowExtras {
  sequencing_notes: string[]
  redundancy_or_repetition: string[]
  misplaced_or_scattered_evidence: string[]
  suggested_moves_or_cuts: string[]
}
interface VMDim {
  key: string
  label: string
  grade: Grade
  assessment: string
  what_works: string
  what_needs_help: string
  recommended_changes: string[]
  flow?: VMFlowExtras
  // legacy trio, rendered only when the report is not dashboard-native
  legacy?: { explanation: string; primary_reason: string; priority_improvement: string }
}
interface VMSlide {
  slide_number?: number
  title: string
  grade: Grade
  assessment: string
  investor_decision: string
  what_works: string
  what_needs_help: string
  recommended_changes: string[]
  evidence_found: string[]
  evidence_missing: string[]
  related_deck_issue: string
}
interface ViewModel {
  native: boolean
  deckScore: VMDeckScore
  dims: VMDim[]
  slides: VMSlide[]
}

const DIM_LABELS: Record<string, string> = {
  completeness: 'Completeness',
  clarity: 'Clarity',
  brevity: 'Brevity',
  flow: 'Flow',
}

function ctxHasAny(c: VMContext | null): boolean {
  if (!c) return false
  return Boolean(c.stage || c.audience || c.target_raise || c.business_type || c.deck_purpose || c.note)
}

// Build the Investment Case view model directly from report_v2.investment_case.
// Content is rendered verbatim; nothing is split, reclassified, or reworded.
function buildInvestmentCase(ic?: InvestmentCaseV2): VMInvestmentCase | null {
  if (!ic) return null
  const area = (a?: InvestmentCaseAssessmentV2): VMICArea | null => {
    if (!a) return null
    const label = (a.label || '').trim()
    const interpretation = (a.interpretation || '').trim()
    if (!label && !interpretation) return null
    return { label, interpretation }
  }
  const vm: VMInvestmentCase = {
    investor_fit: area(ic.investor_fit),
    market_validation: (ic.market_validation || '').trim(),
    opportunity_strength: area(ic.opportunity_strength),
    execution_credibility: area(ic.execution_credibility),
  }
  if (
    !vm.investor_fit &&
    !vm.market_validation &&
    !vm.opportunity_strength &&
    !vm.execution_credibility
  ) {
    return null
  }
  return vm
}

// Top priority improvements, rendered verbatim. Capped at 5 (spec: top 4–5).
function buildPriorityImprovements(list?: PriorityImprovementV2[]): VMPriorityImprovement[] {
  return (list || [])
    .filter((p) => p && (p.title || p.why_it_matters || p.what_to_add_or_change))
    .slice(0, 5)
    .map((p) => ({
      title: (p.title || '').trim(),
      why_it_matters: (p.why_it_matters || '').trim(),
      what_to_add_or_change: (p.what_to_add_or_change || '').trim(),
    }))
}

function _normForDedup(s: string): string {
  return (s || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
}

// Suggested Next Steps, filtered to those NOT duplicative of a priority
// improvement (title match or meaningful substring overlap). This is a
// visibility decision only — surviving steps are rendered verbatim.
function buildNextSteps(
  steps: SuggestedNextStepV2[] | undefined,
  improvements: VMPriorityImprovement[],
): VMNextStep[] {
  const impTitles = improvements.map((p) => _normForDedup(p.title)).filter(Boolean)
  const isDuplicative = (title: string): boolean => {
    const n = _normForDedup(title)
    if (!n) return false
    return impTitles.some((t) => {
      if (t === n) return true
      const [short, long] = t.length <= n.length ? [t, n] : [n, t]
      return short.length >= 8 && long.includes(short)
    })
  }
  return (steps || [])
    .filter((s) => s && (s.title || s.detail))
    .filter((s) => !isDuplicative(s.title || ''))
    .map((s) => ({ title: (s.title || '').trim(), detail: (s.detail || '').trim() }))
}

function buildViewModel(report: PitchDeckCheckReportV2): ViewModel {
  // These richer sections come from top-level report_v2 fields, which are
  // populated on both the dashboard-native and legacy paths.
  const investmentCase = buildInvestmentCase(report.investment_case)
  const priorityImprovements = buildPriorityImprovements(report.priority_improvements)
  const nextSteps = buildNextSteps(report.suggested_next_steps, priorityImprovements)

  const df = report.dashboard_feedback
  if (df) {
    const ds = df.deck_score
    const ec = ds.evaluated_context
    const dims: VMDim[] = (['completeness', 'clarity', 'brevity', 'flow'] as const)
      .map((k) => {
        const d = df.deck_feedback[k]
        if (!d) return null
        const base: VMDim = {
          key: k,
          label: DIM_LABELS[k],
          grade: gradeFromString(d.grade),
          assessment: d.assessment,
          what_works: d.what_works,
          what_needs_help: d.what_needs_help,
          recommended_changes: d.recommended_changes || [],
        }
        if (k === 'flow') {
          const f = df.deck_feedback.flow
          base.flow = {
            sequencing_notes: f.sequencing_notes || [],
            redundancy_or_repetition: f.redundancy_or_repetition || [],
            misplaced_or_scattered_evidence: f.misplaced_or_scattered_evidence || [],
            suggested_moves_or_cuts: f.suggested_moves_or_cuts || [],
          }
        }
        return base
      })
      .filter((x): x is VMDim => x !== null)

    return {
      native: true,
      deckScore: {
        grade: gradeFromString(ds.grade),
        title: ds.title || 'Deck Score',
        summary: ds.summary || '',
        like: ds.investors_will_like || [],
        question: ds.investors_will_question || [],
        pass: ds.what_could_make_investors_pass || [],
        focus: ds.highest_leverage_revision_focus || '',
        investmentCase,
        priorityImprovements,
        nextSteps,
        context: normalizeContext(ec),
      },
      dims,
      slides: (df.slide_feedback || []).map((s) => ({
        slide_number: s.slide_number,
        title: s.title || 'Section',
        grade: gradeFromString(s.grade),
        assessment: s.assessment || '',
        investor_decision: s.investor_decision || '',
        what_works: s.what_works || '',
        what_needs_help: s.what_needs_help || '',
        recommended_changes: s.recommended_changes || [],
        evidence_found: s.evidence_found || [],
        evidence_missing: s.evidence_missing || [],
        related_deck_issue: s.related_deck_issue || '',
      })),
    }
  }

  // --- legacy fallback (older reports without dashboard_feedback) --------------
  const og = report.overall_grade
  const cs = report.context_summary
  const dcs = report.deck_communication_scores
  const dims: VMDim[] = (['completeness', 'clarity', 'brevity', 'flow'] as const)
    .filter((k) => dcs && dcs[k])
    .map((k) => {
      const d = dcs[k]
      return {
        key: k,
        label: DIM_LABELS[k],
        grade: deckScoreToGrade(d.score, d.label),
        assessment: d.label || DASH_LABEL[deckScoreToGrade(d.score, d.label)],
        what_works: '',
        what_needs_help: '',
        recommended_changes: [],
        legacy: {
          explanation: d.explanation,
          primary_reason: d.primary_reason,
          priority_improvement: d.priority_improvement,
        },
      }
    })

  return {
    native: false,
    deckScore: {
      grade: overallLetterToGrade(og?.letter),
      title: report.header?.company_name || 'Deck Score',
      summary: og?.what_this_means || report.primary_diagnosis?.summary || '',
      like: report.what_investors_may_believe || [],
      question: report.what_investors_may_question || [],
      pass: [],
      focus: '',
      investmentCase,
      priorityImprovements,
      nextSteps,
      context: cs
        ? {
            stage: cs.company_context && cs.company_context !== 'Unknown' ? cs.company_context : '',
            audience: cs.intended_investor_audience || '',
            target_raise: cs.target_raise || '',
            deck_purpose: '',
            business_type: '',
            confidence: cs.context_confidence || '',
            note: cs.evaluation_note || '',
          }
        : null,
    },
    dims,
    slides: (report.slide_level_feedback || []).map((s) => ({
      slide_number: s.slide_number,
      title: s.slide_title_or_section || 'Section',
      grade: slideAssessmentToGrade(s.assessment),
      assessment: s.assessment || '',
      investor_decision: s.investor_decision || '',
      what_works: s.what_works || '',
      what_needs_help: s.what_is_missing || '',
      recommended_changes: s.recommended_improvement ? [s.recommended_improvement] : [],
      evidence_found: [],
      evidence_missing: [],
      related_deck_issue: '',
    })),
  }
}

function normalizeContext(ec?: DashboardEvaluatedContextV2): VMContext | null {
  if (!ec) return null
  return {
    stage: ec.stage || '',
    audience: ec.audience || '',
    target_raise: ec.target_raise || '',
    deck_purpose: ec.deck_purpose || '',
    business_type: ec.business_type || '',
    confidence: ec.confidence || '',
    note: ec.note || '',
  }
}

// --- small components ---------------------------------------------------------

function GradeMark({ grade, size = 'md' }: { grade: Grade; size?: 'md' | 'lg' }) {
  const letter = grade === 'neutral' ? '–' : grade
  const textCls = size === 'lg' ? 'text-2xl' : 'text-[15px]'
  const underlineCls = size === 'lg' ? 'mt-0.5 h-0.5 w-7' : 'mt-0.5 h-0.5 w-6'
  return (
    <span className="inline-flex flex-col items-center leading-none shrink-0">
      <span className={`${textCls} font-semibold text-monarch-ink`}>{letter}</span>
      <span className={`rounded-full ${underlineCls} ${GRADE_UNDERLINE[grade]}`} />
    </span>
  )
}

function TriageCard({
  title,
  status,
  grade,
  selected,
  onSelect,
  gradeColumnBg = false,
}: {
  title: string
  status?: string
  grade: Grade
  selected: boolean
  onSelect: () => void
  gradeColumnBg?: boolean
}) {
  const letter = grade === 'neutral' ? '–' : grade
  return (
    <button type="button" onClick={onSelect} className={cardClass(selected)}>
      {/* Grade signal: a full-height colored left rail. Negative insets let it
          cover the border on the left so it runs edge-to-edge with no grey cap
          at top or bottom. Independent of the selection border. */}
      <span
        aria-hidden
        className={`absolute top-[-1px] bottom-[-1px] left-[-1px] w-1 ${GRADE_UNDERLINE[grade]}`}
      />
      <div className="flex items-stretch">
        {/* Grade column: the letter, vertically centered next to the rail, with
            an optional very-pale-gray fill (used on slide cards). */}
        <div
          className={`flex items-center justify-center shrink-0 pl-2.5 pr-2.5 ${
            gradeColumnBg ? 'bg-gray-100' : ''
          }`}
        >
          <span className="text-[15px] font-semibold leading-none text-monarch-ink">{letter}</span>
        </div>
        <div className="min-w-0 flex-1 py-2 pr-3 pl-3">
          <span className="block text-[14px] font-medium text-monarch-ink truncate">{title}</span>
          {status && (
            <p className="mt-0.5 text-[14px] font-normal text-monarch-sub leading-tight truncate">{status}</p>
          )}
        </div>
      </div>
    </button>
  )
}

function DetailRow({ label, children }: { label: string; children: React.ReactNode }) {
  if (!children) return null
  return (
    <div>
      <p className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-1">{label}</p>
      <p className="text-[14px] text-monarch-body leading-normal">{children}</p>
    </div>
  )
}

// Bulleted list for a string[] canonical field. Renders items verbatim.
function DetailList({
  label,
  items,
  markerClass = 'text-monarch-border-strong',
}: {
  label: string
  items?: string[]
  markerClass?: string
}) {
  const list = (items || []).filter((s) => s && s.trim())
  if (list.length === 0) return null
  return (
    <div>
      <p className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-1">{label}</p>
      <ul className="space-y-1">
        {list.map((it, idx) => (
          <li key={idx} className="flex gap-2">
            <span className={`${markerClass} flex-shrink-0`}>•</span>
            <span className="text-[14px] text-monarch-body leading-normal">{it}</span>
          </li>
        ))}
      </ul>
    </div>
  )
}

// One Investment Case area: "Name — Label" heading + verbatim interpretation.
function InvestmentArea({ name, area }: { name: string; area: VMICArea | null }) {
  if (!area || (!area.label && !area.interpretation)) return null
  return (
    <div>
      <p className="text-[14px] font-medium text-monarch-body">
        {name}
        {area.label ? ` — ${area.label}` : ''}
      </p>
      {area.interpretation && (
        <p className="text-[14px] text-monarch-body leading-normal">{area.interpretation}</p>
      )}
    </div>
  )
}

function IssueTag({ issueType }: { issueType?: string }) {
  if (!issueType || issueType === 'None') return null
  return (
    <span className="inline-block text-[14px] font-medium text-monarch-sub bg-monarch-fill rounded-lg px-2 py-0.5">
      {issueType}
    </span>
  )
}

// --- selection ---------------------------------------------------------------

type Selected =
  | { type: 'deck_summary' }
  | { type: 'deck_dim'; index: number }
  | { type: 'slide'; index: number }
  | null

// --- component ----------------------------------------------------------------

export function V2Report({ report }: V2ReportProps) {
  const vm = useMemo(() => buildViewModel(report), [report])
  const { deckScore, dims, slides } = vm

  const [selected, setSelected] = useState<Selected>({ type: 'deck_summary' })
  const detailRef = useRef<HTMLDivElement | null>(null)

  // --- desktop workspace: resizable two-pane split (>= 1280px) ---------------
  const LEFT_MIN = 600
  const RIGHT_MIN = 420
  const DIVIDER_W = 22

  const [isDesktop, setIsDesktop] = useState(false)
  useEffect(() => {
    const mq = window.matchMedia('(min-width: 1280px)')
    const update = () => setIsDesktop(mq.matches)
    update()
    mq.addEventListener('change', update)
    return () => mq.removeEventListener('change', update)
  }, [])

  const containerRef = useRef<HTMLDivElement | null>(null)
  const [containerW, setContainerW] = useState(0)
  useEffect(() => {
    if (!isDesktop) return
    const el = containerRef.current
    if (!el) return
    const ro = new ResizeObserver((entries) => setContainerW(entries[0].contentRect.width))
    ro.observe(el)
    return () => ro.disconnect()
  }, [isDesktop])

  const [leftWidth, setLeftWidth] = useState<number | null>(() => {
    try {
      const v = localStorage.getItem('pdc_report_split')
      return v ? parseInt(v, 10) : null
    } catch {
      return null
    }
  })
  const leftWidthRef = useRef<number | null>(leftWidth)

  const maxLeft = Math.max(LEFT_MIN, containerW - RIGHT_MIN - DIVIDER_W)
  const appliedLeft =
    containerW === 0
      ? null
      : leftWidth != null
      ? Math.min(Math.max(leftWidth, LEFT_MIN), maxLeft)
      : Math.round(containerW * 0.5)

  const onDividerDown = useCallback((e: React.PointerEvent) => {
    e.preventDefault()
    const el = containerRef.current
    if (!el) return
    const rect = el.getBoundingClientRect()
    const onMove = (ev: PointerEvent) => {
      const w = Math.max(LEFT_MIN, Math.min(ev.clientX - rect.left, rect.width - RIGHT_MIN - DIVIDER_W))
      leftWidthRef.current = w
      setLeftWidth(w)
    }
    const onUp = () => {
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
      document.body.style.userSelect = ''
      document.body.style.cursor = ''
      try {
        if (leftWidthRef.current != null) localStorage.setItem('pdc_report_split', String(Math.round(leftWidthRef.current)))
      } catch {
        /* ignore */
      }
    }
    document.body.style.userSelect = 'none'
    document.body.style.cursor = 'col-resize'
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
  }, [])

  const select = (next: Selected) => {
    setSelected(next)
    if (!isDesktop) {
      window.setTimeout(() => detailRef.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }), 50)
    }
  }

  const renderDetail = () => {
    if (!selected) return null
    if (selected.type === 'deck_summary') return <DeckScoreDetail ds={deckScore} />
    if (selected.type === 'deck_dim') {
      const d = dims[selected.index]
      return d ? <DeckDimDetail dim={d} native={vm.native} /> : null
    }
    const s = slides[selected.index]
    return s ? <SlideDetail slide={s} /> : null
  }

  const SLIDE_GRID_STYLE: React.CSSProperties = {
    display: 'grid',
    gap: '0.625rem',
    gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
  }

  const leftContent = (
    <div className="space-y-5">
      {/* Deck Score — one compact selectable summary card */}
      <div>
        <h2 className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-2.5">Grade</h2>
        <TriageCard
          title={deckScore.title}
          status={deckScore.summary}
          grade={deckScore.grade}
          selected={selected?.type === 'deck_summary'}
          onSelect={() => select({ type: 'deck_summary' })}
        />
      </div>

      {dims.length > 0 && (
        <div>
          <h2 className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-2.5">Deck</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-2.5">
            {dims.map((d, i) => (
              <TriageCard
                key={d.key}
                title={d.label}
                status={d.assessment}
                grade={d.grade}
                selected={selected?.type === 'deck_dim' && selected.index === i}
                onSelect={() => select({ type: 'deck_dim', index: i })}
              />
            ))}
          </div>
        </div>
      )}

      {slides.length > 0 && (
        <div>
          <h2 className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-2.5">Slides</h2>
          <div style={SLIDE_GRID_STYLE}>
            {slides.map((s, i) => (
              <TriageCard
                key={i}
                title={s.title}
                status={s.assessment}
                grade={s.grade}
                selected={selected?.type === 'slide' && selected.index === i}
                onSelect={() => select({ type: 'slide', index: i })}
                gradeColumnBg
              />
            ))}
          </div>
        </div>
      )}
    </div>
  )

  const detailPane = (
    <div className="rounded-xl border border-monarch-border bg-monarch-card p-5 sm:p-6 shadow-[0_1px_2px_rgba(0,0,0,0.04)]">
      {renderDetail()}
    </div>
  )

  return (
    <div className="font-sans text-monarch-body">
      {isDesktop ? (
        <div ref={containerRef} className="flex items-stretch">
          <div className="min-w-0 shrink-0" style={{ width: appliedLeft != null ? `${appliedLeft}px` : '50%' }}>
            {leftContent}
          </div>
          <div
            role="separator"
            aria-orientation="vertical"
            title="Drag to resize"
            onPointerDown={onDividerDown}
            className="group relative shrink-0 flex items-center justify-center cursor-col-resize select-none touch-none"
            style={{ width: DIVIDER_W }}
          >
            <div className="absolute inset-y-0 left-1/2 -translate-x-1/2 w-px bg-monarch-border group-hover:bg-[#333] group-active:bg-[#333] transition-colors" />
            <div className="relative z-10 flex flex-col items-center gap-1 rounded-lg border border-monarch-border-strong bg-monarch-card px-1 py-2.5 shadow-[0_1px_2px_rgba(0,0,0,0.04)] group-hover:border-[#333] group-active:border-[#333] transition-colors">
              <span className="w-1 h-1 rounded-full bg-monarch-sub group-hover:bg-[#333] group-active:bg-[#333]" />
              <span className="w-1 h-1 rounded-full bg-monarch-sub group-hover:bg-[#333] group-active:bg-[#333]" />
              <span className="w-1 h-1 rounded-full bg-monarch-sub group-hover:bg-[#333] group-active:bg-[#333]" />
            </div>
          </div>
          {selected && (
            <div className="flex-1 min-w-0">
              {/* Invisible spacer matching the section heading height so the
                  detail pane's top aligns with the top of the grade card. */}
              <h2 aria-hidden className="text-[14px] font-medium uppercase tracking-wide mb-2.5 invisible">&nbsp;</h2>
              <div className="sticky top-6 max-h-[calc(100vh-6rem)] overflow-y-auto">{detailPane}</div>
            </div>
          )}
        </div>
      ) : (
        <div className="space-y-5">
          {leftContent}
          {selected && <div ref={detailRef}>{detailPane}</div>}
        </div>
      )}

      <p className="mt-8 text-[14px] text-monarch-muted leading-normal">
        This report evaluates the deck as presented. It does not predict fundraising success.
      </p>
    </div>
  )
}

// --- selected-detail renderers ------------------------------------------------
//
// Report substance is generated by canonical report generation.
// These components render dashboard_feedback fields directly and must not derive
// or rewrite substantive feedback.

function DeckScoreDetail({ ds }: { ds: VMDeckScore }) {
  return (
    <div>
      <div className="flex items-center gap-4 mb-4">
        <GradeMark grade={ds.grade} size="lg" />
        <div className="min-w-0">
          <p className="text-base font-semibold text-monarch-ink">{ds.title}</p>
          <p className="text-[14px] text-monarch-sub">Overall assessment</p>
        </div>
      </div>
      {ds.summary && <p className="text-[15px] text-monarch-body leading-normal mb-4">{ds.summary}</p>}
      {ds.focus && (
        <div className="mb-4">
          <p className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-1">
            Highest-leverage revision focus
          </p>
          <p className="text-[14px] text-monarch-body leading-normal">{ds.focus}</p>
        </div>
      )}
      <div className="space-y-4">
        <DetailList label="Investors will likely like" items={ds.like} markerClass="text-grade-a" />
        <DetailList label="Investors will likely question" items={ds.question} markerClass="text-grade-c" />
        <DetailList label="What could make investors pass" items={ds.pass} markerClass="text-grade-d" />
      </div>
      {ds.investmentCase && (
        <div className="mt-4">
          <p className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-2">
            Investment Case as Presented
          </p>
          <div className="space-y-2.5">
            <InvestmentArea name="Investor Fit" area={ds.investmentCase.investor_fit} />
            {ds.investmentCase.market_validation && (
              <div>
                <p className="text-[14px] font-medium text-monarch-body">Market Validation</p>
                <p className="text-[14px] text-monarch-body leading-normal">
                  {ds.investmentCase.market_validation}
                </p>
              </div>
            )}
            <InvestmentArea name="Opportunity Strength" area={ds.investmentCase.opportunity_strength} />
            <InvestmentArea name="Execution Credibility" area={ds.investmentCase.execution_credibility} />
          </div>
        </div>
      )}
      {ds.priorityImprovements.length > 0 && (
        <div className="mt-4">
          <p className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-2">
            Top Priority Improvements
          </p>
          <div className="space-y-3">
            {ds.priorityImprovements.map((p, i) => (
              <div key={i}>
                {p.title && <p className="text-[14px] font-medium text-monarch-body">{p.title}</p>}
                {p.why_it_matters && (
                  <p className="text-[14px] text-monarch-body leading-normal">
                    <span className="text-monarch-sub">Why it matters: </span>
                    {p.why_it_matters}
                  </p>
                )}
                {p.what_to_add_or_change && (
                  <p className="text-[14px] text-monarch-body leading-normal">
                    <span className="text-monarch-sub">What to add or change: </span>
                    {p.what_to_add_or_change}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
      {ds.nextSteps.length > 0 && (
        <div className="mt-4">
          <p className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-2">
            Suggested Next Steps
          </p>
          <ul className="space-y-1.5">
            {ds.nextSteps.map((s, i) => (
              <li key={i} className="flex gap-2">
                <span className="text-monarch-border-strong flex-shrink-0">•</span>
                <span className="text-[14px] text-monarch-body leading-normal">
                  {s.title}
                  {s.detail ? ` — ${s.detail}` : ''}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}
      {ctxHasAny(ds.context) && ds.context && (
        // Evaluated context — inferred, shown as secondary. See dashboard_feedback
        // note for the explicit-context-capture TODO.
        <div className="mt-4 pt-3 border-t border-monarch-border">
          <p className="text-[14px] font-medium text-monarch-sub uppercase tracking-wide mb-1">Evaluated as</p>
          <div className="text-[14px] text-monarch-muted leading-normal space-y-0.5">
            {ds.context.stage && <p>Stage: {ds.context.stage}</p>}
            {ds.context.business_type && <p>Business type: {ds.context.business_type}</p>}
            {ds.context.deck_purpose && <p>Deck purpose: {ds.context.deck_purpose}</p>}
            {ds.context.audience && <p>Audience: {ds.context.audience}</p>}
            {ds.context.target_raise && <p>Target raise: {ds.context.target_raise}</p>}
            {ds.context.confidence && <p>Confidence: {ds.context.confidence}</p>}
            {ds.context.note && <p className="pt-1">{ds.context.note}</p>}
          </div>
        </div>
      )}
    </div>
  )
}

function DeckDimDetail({ dim, native }: { dim: VMDim; native: boolean }) {
  return (
    <div>
      <div className="flex items-center gap-4 mb-4">
        <GradeMark grade={dim.grade} size="lg" />
        <div>
          <p className="text-base font-semibold text-monarch-ink">{dim.label}</p>
          <p className="text-[14px] text-monarch-sub">{dim.assessment || DASH_LABEL[dim.grade]}</p>
        </div>
      </div>
      {native ? (
        <div className="space-y-3">
          <DetailRow label="What's working">{dim.what_works}</DetailRow>
          <DetailRow label="What needs help">{dim.what_needs_help}</DetailRow>
          <DetailList label="Recommended changes" items={dim.recommended_changes} />
          {dim.flow && (
            <>
              <DetailList label="Sequencing" items={dim.flow.sequencing_notes} />
              <DetailList label="Redundancy or repetition" items={dim.flow.redundancy_or_repetition} />
              <DetailList label="Misplaced or scattered evidence" items={dim.flow.misplaced_or_scattered_evidence} />
              <DetailList label="Suggested moves or cuts" items={dim.flow.suggested_moves_or_cuts} />
            </>
          )}
        </div>
      ) : (
        // Legacy report: canonical only provides these three fields; render them
        // under their real labels (no forced working/needs-help buckets).
        <div className="space-y-3">
          <DetailRow label="Explanation">{dim.legacy?.explanation}</DetailRow>
          <DetailRow label="Primary reason">{dim.legacy?.primary_reason}</DetailRow>
          <DetailRow label="Priority improvement">{dim.legacy?.priority_improvement}</DetailRow>
        </div>
      )}
    </div>
  )
}

function SlideDetail({ slide }: { slide: VMSlide }) {
  // Hide evidence lists when they merely echo the rows above (the canonical
  // reshaper mirrors what_works/what_needs_help into single-item evidence lists).
  const echoes = (items: string[], other: string) =>
    items.length === 1 && items[0].trim() === other.trim()
  const evidenceFound = echoes(slide.evidence_found, slide.what_works) ? [] : slide.evidence_found
  const evidenceMissing = echoes(slide.evidence_missing, slide.what_needs_help) ? [] : slide.evidence_missing
  return (
    <div>
      <div className="flex items-center gap-4 mb-4">
        <GradeMark grade={slide.grade} size="lg" />
        <div className="min-w-0">
          <p className="text-base font-semibold text-monarch-ink">
            {typeof slide.slide_number === 'number' && slide.slide_number > 0 ? `Slide ${slide.slide_number} · ` : ''}
            {slide.title}
          </p>
          <p className="text-[14px] text-monarch-sub">{slide.assessment || DASH_LABEL[slide.grade]}</p>
        </div>
        {slide.related_deck_issue && (
          <div className="ml-auto">
            <IssueTag issueType={slide.related_deck_issue} />
          </div>
        )}
      </div>
      <div className="space-y-3">
        <DetailRow label="What's working">{slide.what_works}</DetailRow>
        <DetailRow label="What needs help">{slide.what_needs_help}</DetailRow>
        <DetailList label="Recommended changes" items={slide.recommended_changes} />
        <DetailList label="Evidence found" items={evidenceFound} markerClass="text-grade-a" />
        <DetailList label="Evidence missing" items={evidenceMissing} markerClass="text-grade-c" />
        {slide.investor_decision && (
          <p className="text-[14px] text-monarch-muted leading-normal pt-1">
            <span className="font-medium text-monarch-sub">Investor read:</span> {slide.investor_decision}
          </p>
        )}
      </div>
    </div>
  )
}
